### ISSUE TITLE
Appears that pygame should be a required dependency

### ISSUE THREAD

**Issue by nitrohorse** [jcemerson/protonvpn-cli-gui#13]
Hey, thanks for sharing this project! As an FYI I needed to install pygame to bypass the app from crashing during launch.

 - OS: Pop!_OS 19.10 x86_64
 - App Version: v0.1.9-beta

Log prior to installing pygame:
```
$ sudo protonvpn-cli-gui
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_20-03-28_1.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.7/dist-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_pygame, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
egl_rpi - ImportError: cannot import name 'bcm' from 'kivy.lib.vidcore_lite' (/usr/local/lib/python3.7/dist-packages/kivy/lib/vidcore_lite/__init__.py)
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

pygame - ModuleNotFoundError: No module named 'pygame'
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/window/window_pygame.py", line 13, in <module>
    import pygame

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [Text        ] Unable to find any valuable Text provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
pygame - ModuleNotFoundError: No module named 'pygame'
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/text/text_pygame.py", line 18, in <module>
    import pygame

pil - ModuleNotFoundError: No module named 'PIL'
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/local/lib/python3.7/dist-packages/kivy/core/text/text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.
```

Resolution:
```
sudo pip3 install pygame
```

I'm thinking pygame should probably be added as an installed dependency in the setup.py.

**Comment by jcemerson** [comment]
Well, it's not exactly a true dependency because I don't even have pygame.

What _is_ a [dependency for Kivy](https://kivy.org/doc/stable/installation/installation-windows.html#kivy-s-dependencies) is some sort of supported Window provider, of which pygame is one (Pygame is a Python wrapper module for the SDL multimedia library). There's also glew (the default), angle, or sdl2.

Ultimately, which Window provider you require is dependent on various factors determined by your system, so I'm hesitant to require any one single solution. I'm not familiar with Pop!_OS, though I'm going to learn about it now, but it would seem that you didn't already have one of these dependencies.

This is one of the most common issues reported about using Kivy, but it's fairly easy to resolve once you know what the issue is. Several posts can be found on the subject:

[Kivy - windows - Unable to find any valuable Window provider at all](https://stackoverflow.com/questions/40769386/kivy-windows-unable-to-find-any-valuable-window-provider-at-all)

["ImportError: cannot import name bcm" error with running basic kivy app in ubuntu 15.04
#4085 ](https://github.com/kivy/kivy/issues/4085)

[Unable to find any valuable Window provider at all! (with kivy-daily build)
#3002 ](https://github.com/kivy/kivy/issues/3002)

**That said, perhaps the documentation (which isn't even complete yet as I'm still developing the app), could clarify this dependency concern and point people towards these resources and help them find the answer.**

And you're welcome! Thanks for giving it a try and reporting your concern. I appreciate the feedback.

**Comment by jcemerson** [comment]
I noticed that PyGame was deprecated in Kivy 1.11.1. I updated the README.md with a command to install the necessary dependencies for supporting SDL2. If you should find issues with Kivy/PyGame in the future, consider swapping out PyGame for these other dependencies.

**From [Kivy 1.11.1 Release Notes](https://github.com/kivy/kivy/releases/tag/1.11.0):**

**Deprecated**

[#6313]: Pygame has been deprecated. We urge users who have been using pygame to try SDL2 and our other providers. If there are any reasons why Pygame is used instead of SDL2 please let us know so we can fix them.

**Comment by nitrohorse** [comment]
Okay, thanks for the tip @jcemerson 👌🏼
